/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_edd;

import Analizador.Lexer;
import Analizador.parser;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.paint.Color.web;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author willi
 */
public class Vista extends javax.swing.JFrame {

    public ListaCapas estatica;

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_path = new javax.swing.JLabel();
        btn_cargar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_busqueda = new javax.swing.JTextField();
        btn_busqueda = new javax.swing.JButton();
        label_img = new javax.swing.JLabel();
        label_capa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(25, 25, 25));

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(216, 255, 144));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARGA DE ARCHIVOS");

        label_path.setForeground(new java.awt.Color(216, 255, 144));
        label_path.setText("No has cargado ningún archivo");

        btn_cargar.setText("CARGAR");
        btn_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_path, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cargar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_path)
                    .addComponent(btn_cargar))
                .addContainerGap(492, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carga de archivos", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Visualizar capas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(25, 25, 25));

        btn_busqueda.setText("BUSCAR");
        btn_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedaActionPerformed(evt);
            }
        });

        label_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficar/busqueda.png"))); // NOI18N

        label_capa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label_capa.setForeground(new java.awt.Color(215, 255, 144));
        label_capa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_capa.setText("Ingresa el ID de la capa que buscas, si existe se te mostrará su estructura");

        jLabel2.setBackground(new java.awt.Color(25, 25, 25));
        jLabel2.setForeground(new java.awt.Color(215, 255, 144));
        jLabel2.setText("ID capa buscada:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_busqueda))
                    .addComponent(label_capa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_busqueda)
                    .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_capa, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ver capa", jPanel3);

        jPanel4.setBackground(new java.awt.Color(25, 25, 25));

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        txt_id.setToolTipText("Ingresa el id de la capa que quieras ver");

        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Generar imagen", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("Archivo de capa", "cap");
        chooser.setFileFilter(filtro2);
        int resultado = chooser.showOpenDialog(this);
        if (resultado == 0) {
            File archivo = new File(chooser.getSelectedFile().getAbsolutePath());
            String path = chooser.getSelectedFile().getAbsolutePath();
            String nuevo = path;
            label_path.setText("Archivo cargado: " + nuevo);
            String ST;
            try {
                ST = new String(Files.readAllBytes(archivo.toPath()));
                parser obtener = new parser(new Lexer(new StringReader(ST)));
                try {
                    obtener.parse();
                    for (int i = 0; i < 10; i++) {
                        System.out.println("   -----------   ");
                    }
                    obtener.lista_capas.recorrido_inOrden(obtener.lista_capas.getRaiz());
                    estatica = obtener.lista_capas;
                } catch (Exception ex) {
                    Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        } else {
            label_path.setText("No has cargado ningún archivo");
        }
    }//GEN-LAST:event_btn_cargarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String id = txt_id.getText();
        int id_buscar = Integer.parseInt(id);
        Capa encontrada = estatica.buscarCapa(id_buscar);
        if (encontrada != null) {
            generarBotones(encontrada);
        } else {
            System.out.println("no existe");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaActionPerformed
        String id = txt_busqueda.getText();
        int id_buscar = Integer.parseInt(id);
        Capa encontrada = estatica.buscarCapa(id_buscar);
        String path2 = System.getProperty("user.dir");

        String decodedPath = "";
        try {
            decodedPath = URLDecoder.decode(path2, "UTF-8");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (encontrada != null) {
            String todos = encontrada.getDispersa().escribir_todos();
            escribir_doc(todos);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(decodedPath+"/src/Graficar/grafica.jpg").getImage().getScaledInstance(label_img.getWidth(), label_img.getHeight(),Image.SCALE_SMOOTH));
            label_img.setIcon(imageIcon);
        } else {
            System.out.println("no existe");
        }
    }//GEN-LAST:event_btn_busquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    public void generarBotones(int x, int y) {
        JButton[][] matrizBotones = new JButton[y][x];
        int longitudX = (int) panelBotones.getWidth() / x;
        int longitudY = (int) panelBotones.getHeight() / y;

        for (int i = 0; i < x; i++) {
            for (int j = 0; j < y; j++) {
                int posX = (int) i * longitudX;
                int posY = (int) j * longitudY;
                JButton temp = new JButton();
                temp.setBounds(posX, posY, longitudX, longitudY);
                temp.setBackground(awtColor(web("#C83340")));
                if (i == 0 && j == 0) {
                    temp.setText("MATRIZ");
                    temp.setContentAreaFilled(false);
                } else {
                    if (i == 0 && j > 0) {
                        temp.setText((j - 1) + "");
                        temp.setContentAreaFilled(false);
                    }
                    if (j == 0 && i > 0) {
                        temp.setText((i - 1) + "");
                        temp.setContentAreaFilled(false);
                    }
                }
                panelBotones.add(temp);
            }
        }
    }

    public void generarBotones(Capa c) {
        panelBotones.removeAll();
        Matriz m = c.getDispersa();
        m.escribir_todos();
        int y = m.getNoFil();
        int x = m.getNoCol();
        JButton[][] matrizBotones = new JButton[y][x];
        int longitudX = (int) panelBotones.getWidth() / (x + 2);
        int longitudY = (int) panelBotones.getHeight() / (y + 2);
        for (int i = 0; i < x + 2; i++) {
            for (int j = 0; j < y + 2; j++) {
                int posX = (int) i * longitudX;
                int posY = (int) j * longitudY;
                JButton temp = new JButton();
                temp.setBounds(posX, posY, longitudX, longitudY);
                String color = m.obtener_color(i - 1, j - 1);
                if (!color.equalsIgnoreCase("null")) {
                    temp.setBackground(awtColor(web(color)));
                }
                if (i == 0 && j == 0) {
                    temp.setText("MATRIZ");
                    temp.setContentAreaFilled(false);
                } else {
                    if (i == 0 && j > 0) {
                        temp.setText((j - 1) + "");
                        temp.setContentAreaFilled(false);
                    }
                    if (j == 0 && i > 0) {
                        temp.setText((i - 1) + "");
                        temp.setContentAreaFilled(false);
                    }
                }
                panelBotones.add(temp);
            }
        }
        panelBotones.updateUI();
    }

    private static Color awtColor(javafx.scene.paint.Color fxColor) {
        return new Color(
                (float) fxColor.getRed(),
                (float) fxColor.getGreen(),
                (float) fxColor.getBlue(),
                (float) fxColor.getOpacity());
    }

    public void escribir_doc(String texto) {
        String path2 = System.getProperty("user.dir");

        String decodedPath = "";
        try {
            decodedPath = URLDecoder.decode(path2, "UTF-8");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
        try (FileWriter fw = new FileWriter(decodedPath + "/src/Graficar/grafica.txt", false);
                BufferedWriter bw = new BufferedWriter(fw);
                PrintWriter out = new PrintWriter(bw)) {
            out.println(texto);
        } catch (IOException e) {
            //exception handling left as an exercise for the reader
        }
        generar_grafica();
    }

    public void generar_grafica() {
        String path2 = System.getProperty("user.dir");

        String decodedPath = "";
        try {
            decodedPath = URLDecoder.decode(path2, "UTF-8");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            String dotPath = "dot";

            String fileInputPath = decodedPath+"/src/Graficar/grafica.txt";
            String fileOutputPath = decodedPath+"/src/Graficar/grafica.jpg";

            String tParam = "-Tjpg";
            String tOParam = "-o";

            String[] cmd = new String[5];
            cmd[0] = dotPath;
            cmd[1] = tParam;
            cmd[2] = fileInputPath;
            cmd[3] = tOParam;
            cmd[4] = fileOutputPath;

            Runtime rt = Runtime.getRuntime();

            rt.exec(cmd);

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_busqueda;
    private javax.swing.JButton btn_cargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_capa;
    private javax.swing.JLabel label_img;
    private javax.swing.JLabel label_path;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTextField txt_busqueda;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
