
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSP = 10;
  public static final int COMA = 6;
  public static final int PARENTESISC = 3;
  public static final int PARENTESISA = 2;
  public static final int EOF = 0;
  public static final int NUMERO = 4;
  public static final int LLAVEC = 9;
  public static final int LLAVEA = 8;
  public static final int error = 1;
  public static final int PUNTOC = 7;
  public static final int HEXA = 5;
  public static final int NOMBRE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESISA",
  "PARENTESISC",
  "NUMERO",
  "HEXA",
  "COMA",
  "PUNTOC",
  "LLAVEA",
  "LLAVEC",
  "DOSP",
  "NOMBRE"
  };
}

