
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class symImg {
  /* terminals */
  public static final int COMA = 3;
  public static final int EOF = 0;
  public static final int NUMERO = 2;
  public static final int LLAVEC = 5;
  public static final int LLAVEA = 4;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "COMA",
  "LLAVEA",
  "LLAVEC"
  };
}

